language: c
compiler:
  - clang
  - gcc

before_script:
  - cd json-c && ./autogen.sh && cd ..
  - cd libuv && ./autogen.sh && cd ..
  - autoreconf -i -f 

script:
  - ./configure && make && make check
